### ISSUE TITLE
Hack FS pending issues

### ISSUE THREAD

**Issue by HabacucMX** [zenbitETH/Bright-Forest#7]
Backend
- [ ] RPC for contracts interaction on polygon testnet
- [ ] External database wiring 
- [ ] BF Contracts deployment

Test trip
- [x] Define origin and destination for 2 fixed trips

User data
- [ ] Define tableland, ipfs to manage data from google API
- [x] Track energy rewards and places coordinates from Punk Cities contract
- [x] Set a energy units / distance relationship for Trip rewards

Trip circom integration on frontend
- [x] Step1 go to origin coordinates 
- [x] Step2 start trip
- [x] Step3 ongoing trip
- [x] Step4 finish the trip
- [x] Energy units delivery 
- [x] Store data for a past trip id
- [x] Display trip id on past trips

User interface
- [ ] Wallet wiring 
- [x] Home screen (Locked screen) #9 
- [x] Trip steps breakpoints #10 
- [x] Available trips with breakpoints #11 
- [ ] Set home as locked screen and available trips as unlocked screen
- [x] Past trips  #12 
- [x] Leaderboard #13 
- [x] Live test for video

Hack FS submission
- [x] Readme 
- [x] Backgrounds for video
- [x]  Logo
- [x]  3 snapshots
- [x]  4 Minutes video
- [x]  Fill project submission on the dashboard
- [x]  🏁 Submit the project and choose the judging time🏁
